name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      # Als de projectmap nog geen platformmappen heeft, genereer ze in CI
      - name: Ensure Flutter project scaffolding exists
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Fetch dependencies
        run: flutter pub get

      # Optioneel: snelle check dat assets gevonden worden
      - name: Verify assets exist
        run: ls -la assets/data || true

      - name: Build release APK (per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: leanralanguage-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
